### ISSUE TITLE
Add Venu SQ

### ISSUE THREAD

**Issue by GiulioCocconi** [forsb/Ticker#1]
My smartwatch, Venu Sq, isn't currently supported. Can you add It? Thanks

**Comment by filarl** [comment]
Hi! Thanks for your feedback! This app is not intended for devices with touch screens, since they are missing some buttons and have gestures instead. Venu Sq is also has a different screen than most devices. I therefore need someone to test this to make sure that the app still works and looks as intended. If you are interested in testing an unofficial version of the app that I have made working on your device and post some pictures of it, I could officially add it as a supported device. 

Let me know if you are interested in this and I will post a binary you can load to your device in this thread.

**Comment by GiulioCocconi** [comment]
I made by version based on your source...im using it privately (it's not on the public store)
